#!/bin/bash --login
# IMPORTANT: Run this script DIRECTLY on the frontend (NOT via sbatch)!
# Usage from frontend:
#   tmux new -s pypsa        (start a persistent session)
#   bash run_head.job        (inside tmux)
#
# Submitting via sbatch causes snakemake to run on a compute node, which:
#   1. Creates a Gurobi session on the compute node (counts against your WLS license)
#   2. Gets cancelled when the head SLURM job hits its time limit
#   3. Is explicitly warned against by snakemake itself

export GRB_LICENSE_FILE=/home/users/a/agma/gurobi.lic

cd /beegfs/scratch/agma/pypsa-rsa
mkdir -p logs

SNAKEMAKE='/beegfs/scratch/agma/envs/pypsa-rsa/bin/snakemake'

$SNAKEMAKE solve_all \
    --executor slurm \
    --default-resources \
        "slurm_partition=standard" \
        "mem_mb=16000" \
        "runtime=20000" \
        "slurm_mail_type=END,FAIL" \
        "slurm_mail_user=agatha.majcher@tu-berlin.de" \
    --resources solver_slots=2 \
    --jobs 16 \
    --latency-wait 120 \
    --rerun-incomplete \
    # -F \
    --keep-going \
    2>&1 | tee logs/snakemake_head_$(date +%Y%m%dT%H%M%S).log
