name: pypsa-rsa
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - atlite[version='>=0.2.9']
  - cartopy
  - country_converter
  - dask
  - descartes
  - fiona
  - geopandas[version='>=1']
  - geopy
  - glpk
  - graphviz
  - ipython
  - linopy
  - lxml
  - matplotlib
  - memory_profiler
  - netcdf4
  - networkx
  - numpy=1.26.*
  - openpyxl!=3.1.1
  - pandas=2.2.*
  - pip
  - powerplantmatching[version='>=0.5.15']
  - pre-commit
  - proj
  - pycountry
  - pypsa=0.35.2
  - pyscipopt
  - pytables
  - python[version='>=3.8']
  - pytz
  - pyxlsb
  - rasterio!=1.2.10
  - rioxarray
  - scipy
  - seaborn
  - shapely[version='>=2.0']
  - snakemake-minimal=8.30.0
  - tabula-py
  - tqdm
  - xarray=2025.*
  - xlrd
  - yaml
  - ipykernel
  - tsam
